---
title: Hello World
author: Oliver P. Madsen
date: '2020-11-06'
categories:
  - introduction
  - R
tags:
  - blog
slug: hello-world
---

# Welcome to my blog
First and foremost welcome to my blog. This is a project that I have long been 
intending to start and which is now seeing the light of day. On this blog I'll be looking into problems of my interest. These could be tutorials, my path through learning a new R package, Python module or a piece of software in general. While I will likely be primarily focusing on problems that are in some way related to R, they may also be purely statistical, mathematical or similar.

## Who the h*** am I?
That is a great question. First and foremost, my name is Oliver P. Madsen and I'm a M.sc. Mathematics and Economics graduate where I specialized in theoretical and applied statistics using generalized linear mixed effect models, a type of hierachical models very similar to econometric models. I've worked in Finance, University Education, Research, Data Engineering, Credit Risk, Data Science and have touched foot within Pharma.  
I'm a professional Database Administrator and an R enthusiast. Note that when I say R enthusiast, I am truely down the deep end. I've worked in Python, R, Javascript, VBA, C++, C, C#, Java.. and there is no langauge as intuitive as R. Throughout my studies I was taught in R by Peter Dalgaard (R core) and while he opened my eyes to the wonder of Statistics to an even larger degree opened my eyes to the simplicity of R. It is not the best language for all problems, but it is the simplest language for most scripting and statistics problems.

## The first projects coming up!
While it is an incredible interpreted language I know that it has many flaws. Some of these flaws are what I intend to start covering. For my initial project I'll be looking at commandline arguments, showcase how we can incorporate these in the existing R framework and extensions for interpreting commandline arguments.

It can come as no surprise that I believe *all* of the existing extensions are flawed or missing. Once I've gone through a few examples of existing frameworks, my next project will be looking into creating my own take on a commandline interpreter. Here I'll base my package on one of the existing frameworks but I'll be much more ambitious!  
While looking at some of the existing extensions I might spent a bit some time looking at the source code for the packages, and point out some of the parts that I found interesting and which I'll be reusing for my own attempt.

I intend to write a new blogpost regularly, and while I'll strive to keep them in order I am going to be frank and say that I tend to walk along different tangents. 


